MOODS = {
    'default': 'neutral',
    'options': [
        {'name': 'Нейтральное', 'value': 'neutral'},
        {'name': 'Напряженное', 'value': 'tense'},
        {'name': 'Мрачное', 'value': 'dark_and_gothic'},
        {'name': 'Оптимистичное', 'value': 'light_and_optimistic'},
        {'name': 'Трагическое', 'value': 'tragic'},
        {'name': 'Комическое и абсурдное', 'value': 'comedic_and_absurd'},
        {'name': 'Меланхоличное', 'value': 'melancholic'},
        {'name': 'Романтичное', 'value': 'romantic'},
        {'name': 'Мистическое', 'value': 'mystical'},
        {'name': 'Фантастическое', 'value': 'fantastic'},
        {'name': 'Ужасающее', 'value': 'horrifying'},
        {'name': 'Идиллическое', 'value': 'idyllic'},
        {'name': 'Саркастичное', 'value': 'sarcastic'},
        {'name': 'Ироничное', 'value': 'ironic'},
        {'name': 'Эпичное', 'value': 'epic'},
        {'name': 'Лирическое', 'value': 'lyrical'},
        {'name': 'Драматичное', 'value': 'dramatic'},
        {'name': 'Сатирическое', 'value': 'satirical'},
        {'name': 'Философское', 'value': 'philosophical'},
        {'name': 'Психологическое', 'value': 'psychological'},
        {'name': 'Экзистенциальное', 'value': 'existential'},
        {'name': 'Сюрреалистичное', 'value': 'surreal'},
    ]
}